[versions]
revanced-patcher = "21.0.0"
# Tracking https://github.com/google/smali/issues/64.
#noinspection GradleDependency
smali = "3.0.5"
gson = "2.13.1"
agp = "8.2.2"
annotation = "1.9.1"
preference = "1.2.1"
collections4 = "4.5.0"
lang3 = "3.18.0"
okhttp3 = "4.12.0"
regex = "1.1.11"

[libraries]
gson = { module = "com.google.code.gson:gson", version.ref = "gson" }
annotation = { module = "androidx.annotation:annotation", version.ref = "annotation" }
preference = { module = "androidx.preference:preference", version.ref = "preference" }
collections4 = { module = "org.apache.commons:commons-collections4", version.ref = "collections4" }
lang3 = { module = "org.apache.commons:commons-lang3", version.ref = "lang3" }
okhttp3 = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttp3" }
regex = { module = "com.github.florianingerl.util:regex", version.ref = "regex" }


[plugins]
android-library = { id = "com.android.library", version.ref = "agp" }